name: my first git action work
on:
  push:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4 
      - name: executing remote ssh command 
        uses: appleboy/ssh-action@v1.0.3
        with:
         host: ${{ secrets.EC2_HOST }}
         username: ${{ secrets.EC2_USER }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
            cd /home/ubuntu/cloudStore_backend
            git pull
            npm install
            pm2 restart ecosystem.config.cjs
      - name: Notify on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: "GitHub action failed : ${{ github.repository }}"
          to: vshekhawat136@gmail.com
          from: GitHub Actions Alert
          body: |
             the ci/cd pipeline failed on branch ${{ github.ref_name }},
             Commit: ${{ github.sha }}
             Author: ${{ github.actor }}


             View details here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          subject: "🚀 Deployment Successful: ${{ github.repository }}"
          to: vshekhawat136@gmail.com
          from: GitHub Actions Alert
          body: |
            Great news! The CI/CD pipeline successfully deployed your latest changes to EC2.

            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}

            View run details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}